DATASETS:
  TEST: !!python/tuple
  - sartorius_val
  TRAIN: !!python/tuple
  - sartorius_train
INPUT:
  MASK_FORMAT: bitmask
MODEL:
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x/138205316/model_final_a3ec72.pkl
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    NUM_CLASSES: 3
    SCORE_THRESH_TEST: 0.5
SEED: 2021
SOLVER:
  AMP:
    ENABLED: true
  BASE_LR: 0.0025
  IMS_PER_BATCH: 2
  WARMUP_METHOD: linear
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  STEPS: ()
  MAX_ITER: 10000
TEST:
  EVAL_PERIOD: 242