DATASETS:
  TEST: !!python/tuple
  - sartorius_val
  TRAIN: !!python/tuple
  - sartorius_train
INPUT:
  MASK_FORMAT: bitmask
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN:
  - 480
  - 520
  - 560
  - 640
  - 672
  - 704
  - 736
  - 768
  - 800

MODEL:
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
    NUM_CLASSES: 3
    SCORE_THRESH_TEST: 0.5
SEED: 42
SOLVER:
  AMP:
    ENABLED: true
  BASE_LR: 0.01
  IMS_PER_BATCH: 2
  MAX_ITER: 10000
  LR_SCHEDULER_NAME: OneCycleLR
TEST:
  EVAL_PERIOD: 242
VERSION: 2
