DATASETS:
  TEST: !!python/tuple
  - sartorius_val
  TRAIN: !!python/tuple
  - sartorius_train
INPUT:
  MASK_FORMAT: bitmask

MODEL:
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    NUM_CLASSES: 3
    SCORE_THRESH_TEST: 0.4
SEED: 42
SOLVER:
  AMP:
    ENABLED: true
  GAMMA: 0.1
  BASE_LR: 0.0025
  IMS_PER_BATCH: 2
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  STEPS: (8000,)
  MAX_ITER: 10000
TEST:
  EVAL_PERIOD: 1000
VERSION: 2
